### PR TITLE
Fixed assets loading bug in Expo SDK >= 31

### PR DESCRIPTION
**Pull request by tomermoshe**

### CODE REVIEW

**Comment by pieterbeulque** [comment]
I _think_ this will also need the expo-asset-utils version upgrade I proposed here: https://github.com/expo/expo-asset-utils/pull/12

**Comment by pavlo-paliychuk-insighty** [comment]
I would really appreciate if someone could merge this PR, as it makes this library usable with expo 32

**Comment by pieterbeulque** [comment]
@tomermoshe - You can close this PR as a fix was merged into master & the 1.0.0 release.

**Comment by tomermoshe** [comment]
Great!

**Pull request closed without merging**
